# Generated by Django 3.2.4 on 2021-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0002_remove_banner_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='animation',
            field=models.ManyToManyField(related_name='animation_banner', to='sitewebapp.Animation'),
        ),
    ]
