# Generated by Django 3.2.4 on 2021-06-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0003_banner_animation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animation',
            options={'verbose_name': 'Animation Banner', 'verbose_name_plural': 'Animation Banners'},
        ),
    ]
