# Generated by Django 3.2.4 on 2021-06-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0005_configuration_education_experience_project_social_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='animation',
        ),
    ]
